import type { Toolkit } from "../types";
import HUB_CATALOG_SNAPSHOT from "./hub-catalog.json";

/**
 * The baked hub-catalog snapshot (public Composio toolkit metadata: slugs,
 * names, logos, categories — regenerated by scripts/generate-hub-catalog.mjs
 * and refreshed weekly by CI). At runtime HubCatalogSource layers a fetched
 * copy of the same file over this, so the browse grid stays current between
 * releases; this constant is the offline floor, never the ceiling.
 */
export const HUB_APP_CATALOG: Toolkit[] = HUB_CATALOG_SNAPSHOT as Toolkit[];

/**
 * The bounded set the hub is ASKED about when listing connections: one
 * MANAGE_CONNECTIONS call carries one entry per toolkit, so probing all
 * ~1000 would be a huge, slow request. Instead we probe the popular apps
 * plus every toolkit this install has ever connected (recorded in the auth
 * store), which by construction covers everything that can be active.
 */
export const HUB_PROBE_SLUGS: string[] = [
  "airtable",
  "asana",
  "calendly",
  "clickup",
  "discord",
  "dropbox",
  "figma",
  "github",
  "gitlab",
  "gmail",
  "googlecalendar",
  "googledocs",
  "googledrive",
  "googlesheets",
  "hubspot",
  "intercom",
  "jira",
  "linear",
  "linkedin",
  "mailchimp",
  "microsoft_teams",
  "monday",
  "notion",
  "onedrive",
  "outlook",
  "pipedrive",
  "quickbooks",
  "reddit",
  "salesforce",
  "shopify",
  "slack",
  "stripe",
  "supabase",
  "trello",
  "twitter",
  "typeform",
  "xero",
  "youtube",
  "zendesk",
  "zoom",
];
