import type { Toolkit } from "../types";
import { HUB_CATALOG_DATA } from "./hub-catalog-data";

/**
 * The browsable app catalog a Composio hub offers: the full public toolkit
 * snapshot (see hub-catalog-data.ts, ~1000 apps with names/logos/categories),
 * regenerated by scripts/generate-hub-catalog.mjs. The hub's MCP surface can
 * manage and execute all of them but exposes no browse call, so the
 * Integrations page ships this snapshot.
 */
export const HUB_APP_CATALOG: Toolkit[] = HUB_CATALOG_DATA;

/**
 * The bounded set the hub is ASKED about when listing connections: one
 * MANAGE_CONNECTIONS call carries one entry per toolkit, so probing all
 * ~1000 would be a huge, slow request. Instead we probe the popular apps
 * plus every toolkit this install has ever connected (recorded in the auth
 * store), which by construction covers everything that can be active.
 */
export const HUB_PROBE_SLUGS: string[] = [
  "airtable",
  "asana",
  "calendly",
  "clickup",
  "discord",
  "dropbox",
  "figma",
  "github",
  "gitlab",
  "gmail",
  "googlecalendar",
  "googledocs",
  "googledrive",
  "googlesheets",
  "hubspot",
  "intercom",
  "jira",
  "linear",
  "linkedin",
  "mailchimp",
  "microsoft_teams",
  "monday",
  "notion",
  "onedrive",
  "outlook",
  "pipedrive",
  "quickbooks",
  "reddit",
  "salesforce",
  "shopify",
  "slack",
  "stripe",
  "supabase",
  "trello",
  "twitter",
  "typeform",
  "xero",
  "youtube",
  "zendesk",
  "zoom",
];
