import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import ts from "typescript";
import { arrowExpressionBody } from "./assistant-ast.ts";
import {
  ASSISTANT_GROUPS,
  type AssistantOperation,
  type AssistantParameter,
  type ExtractionResult,
  type UnroutableOperation,
} from "./assistant-catalog-types.ts";
import {
  type Declaration,
  isPlumbingParameter,
  readFileSurface,
} from "./assistant-declarations.ts";
import {
  humanizeMethodName,
  leadingJsDoc,
  parseAssistantDocs,
} from "./assistant-jsdoc.ts";
import type { PathHelper } from "./assistant-path-parts.ts";
import { repoRelative } from "./assistant-paths.ts";
import { extractRoute } from "./assistant-route.ts";
import { isFallback, schemaForType } from "./assistant-schema.ts";

const CATALOG_COMMENT =
  "Generated by pnpm gen:assistant-catalog from the live engine adapter (packages/web/src/engine-adapter). Do not edit. Every `path` is the FULL host path — nothing is prepended to it. A route carries its JSON body EITHER as `body` (one parameter sent whole) OR as `bodyFields` (body key -> parameter); a caller that reads only `body` sends an empty body for every `bodyFields` route. Each path parameter says how its value is escaped: `segment` is one URL segment, `path` keeps the `/` separators of a relative path. Every route returns the host response verbatim; `rawResponse: true` flags the ones whose adapter function additionally post-processes it (unwrapping `items`, 404 fallbacks, `.then` transforms), which a caller driving the route directly does not get.";

export interface ExtractOptions {
  /** Files whose published functions become operations, in precedence order. */
  operationSources: string[];
  /** Read only for the path helpers its templates share. */
  transportSource: string;
}

/** Module-scope arrow helpers a file exports for other files' templates. */
function sharedHelpers(source: ts.SourceFile): Map<string, PathHelper> {
  const helpers = new Map<string, PathHelper>();
  const visit = (node: ts.Node): void => {
    if (ts.isVariableStatement(node)) {
      for (const declaration of node.declarationList.declarations) {
        const arrow = declaration.initializer
          ? arrowExpressionBody(declaration.initializer)
          : null;
        if (arrow && ts.isIdentifier(declaration.name))
          helpers.set(declaration.name.text, arrow);
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  return helpers;
}

/** sha256 over every source the catalog is derived from, path included. */
function hashSources(paths: string[]): string {
  const hash = createHash("sha256");
  for (const path of paths)
    hash.update(`${repoRelative(path)}\n${readFileSync(path, "utf8")}\n`);
  return hash.digest("hex");
}

interface Collected {
  operations: AssistantOperation[];
  undocumented: string[];
  ungrouped: string[];
  misgrouped: string[];
  unschematized: string[];
  unroutable: UnroutableOperation[];
}

/** The parameter names a caller supplies, which is all a route may read. */
function callerParameters(declaration: Declaration): Set<string> {
  return new Set(
    declaration.node.parameters
      .filter((parameter) => !isPlumbingParameter(parameter))
      .flatMap((parameter) =>
        ts.isIdentifier(parameter.name) ? [parameter.name.text] : [],
      ),
  );
}

function parametersOf(
  declaration: Declaration,
  checker: ts.TypeChecker,
  source: ts.SourceFile,
  unschematized: string[],
): AssistantParameter[] {
  return declaration.node.parameters
    .filter((parameter) => !isPlumbingParameter(parameter))
    .map((parameter) => {
      const name = parameter.name.getText(source);
      const schema = schemaForType(
        checker,
        checker.getTypeAtLocation(parameter),
        parameter,
      );
      if (isFallback(schema)) unschematized.push(`${declaration.name}.${name}`);
      return {
        name,
        required: !parameter.questionToken && !parameter.initializer,
        schema,
      };
    });
}

function returnsOf(
  declaration: Declaration,
  checker: ts.TypeChecker,
): ts.Type | null {
  const signature = checker.getSignatureFromDeclaration(declaration.node);
  return signature ? checker.getReturnTypeOfSignature(signature) : null;
}

export function extractCatalog(options: ExtractOptions): ExtractionResult {
  const files = [...options.operationSources, options.transportSource];
  const program = ts.createProgram(files, {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: true,
    skipLibCheck: true,
  });
  const checker = program.getTypeChecker();
  const transport = program.getSourceFile(options.transportSource);
  if (!transport) throw new Error(`Could not load ${options.transportSource}.`);
  const shared = sharedHelpers(transport);
  const collected: Collected = {
    operations: [],
    undocumented: [],
    ungrouped: [],
    misgrouped: [],
    unschematized: [],
    unroutable: [],
  };
  const seen = new Set<string>();

  for (const path of options.operationSources) {
    const source = program.getSourceFile(path);
    if (!source) throw new Error(`Could not load ${path}.`);
    const text = readFileSync(path, "utf8");
    const surface = readFileSurface(source);
    for (const declaration of surface.declarations) {
      if (seen.has(declaration.name)) continue;
      // Route first, schemas second: a declaration that never reaches the wire
      // is not an operation, and typing its parameters would file coverage
      // gaps against a function the catalog does not contain.
      const routing = extractRoute(declaration, callerParameters(declaration), {
        surface,
        shared,
      });
      // Nothing reaches the wire: a pure client-side computation, not an
      // operation a caller could ever dispatch.
      if (routing.reason === "no request call") continue;
      seen.add(declaration.name);
      const params = parametersOf(
        declaration,
        checker,
        source,
        collected.unschematized,
      );
      if (routing.reason !== null)
        collected.unroutable.push({
          name: declaration.name,
          reason: routing.reason,
        });
      const docs = parseAssistantDocs(
        leadingJsDoc(text, declaration.node.getStart(source)),
      );
      if (!docs.description) collected.undocumented.push(declaration.name);
      if (!docs.group) collected.ungrouped.push(declaration.name);
      else if (!ASSISTANT_GROUPS.includes(docs.group))
        collected.misgrouped.push(`${declaration.name}: ${docs.group}`);
      const returnType = returnsOf(declaration, checker);
      const returns = returnType
        ? schemaForType(checker, returnType, declaration.node)
        : { $comment: "unschematized: unknown" };
      if (isFallback(returns))
        collected.unschematized.push(`${declaration.name}.returns`);
      collected.operations.push({
        name: declaration.name,
        group: docs.group ?? "system",
        description: docs.description ?? humanizeMethodName(declaration.name),
        confirm: docs.confirm,
        hidden: docs.hidden,
        params,
        returns,
        route: routing.route,
      });
    }
  }

  collected.operations.sort(
    (left, right) =>
      left.group.localeCompare(right.group) ||
      left.name.localeCompare(right.name),
  );
  collected.unroutable.sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  return {
    catalog: {
      $comment: CATALOG_COMMENT,
      version: 3,
      sourceHash: hashSources(files),
      operations: collected.operations,
    },
    coverage: {
      undocumented: collected.undocumented,
      ungrouped: collected.ungrouped,
      misgrouped: collected.misgrouped,
      unschematized: collected.unschematized,
      hidden: collected.operations
        .filter((operation) => operation.hidden)
        .map((operation) => operation.name),
      unroutable: collected.unroutable,
    },
  };
}
