import type {
  Acknowledgement,
  AssistantCatalog,
  ExtractionResult,
  UnroutableOperation,
} from "./assistant-catalog-types.ts";
import { acknowledgements } from "./assistant-gate.ts";

export function renderCatalog(catalog: AssistantCatalog): string {
  return `${JSON.stringify(catalog, null, 2)}\n`;
}

export function renderCapabilities(catalog: AssistantCatalog): string {
  const visible = catalog.operations.filter((operation) => !operation.hidden);
  const groups = [...new Set(visible.map((operation) => operation.group))];
  const lines = [
    "<!-- Generated by pnpm gen:assistant-catalog from packages/web/src/engine-adapter. Do not edit. -->",
    "# Houston assistant capabilities",
    "",
    "Everything the assistant can do in Houston, derived from the live engine adapter.",
    "",
    "Calling an operation returns the host's raw response. Where the adapter function also post-processes that response (unwrapping `items`, 404 fallbacks), the catalog records it as `rawResponse` and the post-processing is not applied.",
  ];
  for (const group of groups) {
    lines.push("", `## ${group}`, "");
    for (const operation of visible.filter((item) => item.group === group)) {
      lines.push(
        `- \`${operation.name}\`: ${operation.description}${operation.confirm ? " **Confirmation required.**" : ""}${operation.route ? "" : " (not callable yet)"}`,
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

function section(title: string, values: string[]): string[] {
  return [
    `## ${title} (${values.length})`,
    "",
    ...(values.length > 0
      ? values.map((value) => `- \`${value}\``)
      : ["None."]),
  ];
}

function unroutableSection(values: UnroutableOperation[]): string[] {
  return [
    `## Unroutable operations (${values.length})`,
    "",
    "No HTTP route could be derived conservatively from the function body, so the operation is not callable.",
    "",
    ...(values.length > 0
      ? values.map(({ name, reason }) => `- \`${name}\`: ${reason}`)
      : ["None."]),
  ];
}

function acknowledgedSection(
  title: string,
  lead: string,
  values: Acknowledgement[],
): string[] {
  return [
    `## ${title} (${values.length})`,
    "",
    lead,
    "",
    ...(values.length > 0
      ? values.map(
          ({ name, kind, reason }) => `- \`${name}\` — ${kind}: ${reason}`,
        )
      : ["None."]),
  ];
}

export function renderCoverage({
  catalog,
  coverage,
  annotations,
}: ExtractionResult): string {
  const stated = acknowledgements(annotations);
  const debt = stated.filter((item) => item.debt);
  const exceptions = stated.filter((item) => !item.debt);
  const documented = catalog.operations.length - coverage.undocumented.length;
  const rawResponse = catalog.operations.filter(
    (operation) => operation.route?.rawResponse,
  ).length;
  return `${[
    "<!-- Generated by pnpm gen:assistant-catalog from packages/web/src/engine-adapter. Do not edit. -->",
    "# Houston assistant catalog coverage",
    "",
    `- Operations: ${catalog.operations.length}`,
    `- Documented: ${documented}`,
    `- Undocumented: ${coverage.undocumented.length}`,
    `- Ungrouped: ${coverage.ungrouped.length}`,
    `- Unschematized: ${coverage.unschematized.length}`,
    `- Hidden: ${coverage.hidden.length}`,
    `- Routable: ${catalog.operations.length - coverage.unroutable.length}`,
    `- Unroutable: ${coverage.unroutable.length}`,
    `- Raw-response routes: ${rawResponse}`,
    `- Acknowledged exceptions: ${exceptions.length}`,
    `- Acknowledged debt: ${debt.length}`,
    "",
    "A raw-response route reaches the host through an adapter function that post-processes the reply (unwrapping `items`, 404 fallbacks, `.then` transforms). The route itself carries the host's response unchanged.",
    "",
    ...acknowledgedSection(
      "Acknowledged exceptions",
      "Every operation the assistant cannot drive states why in its `@assistant` tag, and `pnpm check:assistant-coverage` fails the build on any that does not. These are the human-owned exceptions.",
      exceptions,
    ),
    "",
    ...acknowledgedSection(
      "Acknowledged debt",
      "Exceptions whose author says the operation SHOULD be automatable and is waiting on a refactor.",
      debt,
    ),
    "",
    ...section("Undocumented operations", coverage.undocumented),
    "",
    ...section("Ungrouped operations", coverage.ungrouped),
    "",
    ...section("Operations outside the group taxonomy", coverage.misgrouped),
    "",
    ...section("Unschematized fields", coverage.unschematized),
    "",
    ...section("Hidden operations", coverage.hidden),
    "",
    ...unroutableSection(coverage.unroutable),
  ].join("\n")}\n`;
}
